name: todo_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_slidable: ^0.6.0
  get: ^4.3.8
  path_provider: ^2.0.2
  reorderables: ^0.4.1
  sqflite: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.7.2

flutter:
  uses-material-design: true

  fonts:
    - family: CascadiaCode
      fonts:
        - asset: fonts/CascadiaCode.ttf
